<?xml version="1.0" encoding="UTF-8"?>
<SCL xmlns="http://www.iec.ch/61850/2003/SCL"
  xmlns:esldoscd="https://openscd.org/SCL/SSD/SLD/v0" version="2007" revision="B">
  <Header id="development sample"/>
  <Substation name="S1">
    <Private type="OpenSCD-SLD-Layout">
      <esldoscd:SLDAttributes esldoscd:w="50" esldoscd:h="25"/>
    </Private>
    <VoltageLevel name="V1">
      <Private type="OpenSCD-SLD-Layout">
        <esldoscd:SLDAttributes esldoscd:x="1" esldoscd:y="1" esldoscd:lx="1" esldoscd:ly="1" esldoscd:w="48" esldoscd:h="22"/>
      </Private>
      <Bay name="B2">
        <Private type="OpenSCD-SLD-Layout">
          <esldoscd:SLDAttributes esldoscd:x="14" esldoscd:y="2" esldoscd:lx="14" esldoscd:ly="2" esldoscd:w="12" esldoscd:h="20"/>
        </Private>
      </Bay>
      <Bay name="B1">
        <Private type="OpenSCD-SLD-Layout">
          <esldoscd:SLDAttributes esldoscd:x="2" esldoscd:y="2" esldoscd:lx="2" esldoscd:ly="2" esldoscd:w="11" esldoscd:h="20"/>
        </Private>
      </Bay>
    </VoltageLevel>
  </Substation>
</SCL>
